<a href="https://colab.research.google.com/github/Dennischegemwangi/code-base/blob/main/Transformers_(hugging_face).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from transformers import pipeline

classifier = pipeline("text-classification")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu

In [5]:
#Text classification
import pandas as pd

output=classifier (text)
pd.DataFrame(output)

      label     score
0  POSITIVE  0.716504

In [6]:
#named entity recognition
ner_tagger = pipeline ("ner", aggregation_strategy= "simple")
Outputs = ner_tagger(text)
pd.DataFrame(Outputs)

[transformers] No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.33GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.bias   | UNEXPECTED |  |
bert.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

  entity_group     score     word  start  end
0          ORG  0.916628    Jumia     62   67
1          LOC  0.431051  ##ianja     76   81

In [6]:
text = " I was asking for a refund for the product that I returned at Jumia branch kianjai, I would kindly appreciate if you respond on time since it is required for my work, urgently without any delay.For more details here are my contacts"

In [ ]:
!pip install "transformers<5"

In [7]:
#Text summarization
reader = pipeline ("summarization")
Output = reader ( text,max_length = 50,clean_up_tokenization_spaces = True)
print (Output [0]['summary_text'])

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu
Your min_length=56 must be inferior than your max_length=50.
/usr/local/lib/python3.13/dist-packages/transformers/generation/utils.py:1633: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (50). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length.
  warnings.warn(

 I was asking for a refund for the product that I returned at Jumia branch kianjai, I would kindly appreciate if you respond on time since it is required for my work, urgently without any delay. For more details

In [11]:
#Translation
translator = pipeline("translation_en_to_de",model ="Helsinki-NLP/opus-mt-en-sw")
output = translator(text,clean_up_tokenization_spaces = True,max_length = 100)
print(output[0]['translation_text'])

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/300M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/300M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/821k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/813k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

Device set to use cpu

Nilikuwa nikimwomba msaada wa bidhaa niliyorudi kwa haraka katika ofisi ya tawi ya Jimia kianjai, kwa fadhili ningethamini kama mtaitikia kwa wakati kwa sababu inahitajika kwa kazi yangu, haraka bila kukawia.

In [12]:
#Text generation
generator = pipeline("text-generation")
response = "Dear customer,we were sorry for the delay of your refund,our customer services will reach you soon"
prompt = text + "\n\n customer care:\n"+ response
output = generator(prompt,max_length = 100)
print(output[0]['generated_text'])

No model was supplied, defaulted to openai-community/gpt2 and revision 607a30d (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=100) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

 I was asking for a refund for the product that I returned at Jumia branch kianjai, I would kindly appreciate if you respond on time since it is required for my work, urgently without any delay.For more details here are my contacts

 customer care:
Dear customer,we were sorry for the delay of your refund,our customer services will reach you soon.


Thank you for your time.


XOXOXO

1. I received a refund for a product that I did not return. The company did not send me the product within 14 days of receipt of the product.


2. As you can see from the picture in the picture, the product was not returned. It could have been refunded to the customer by the company.

3. Thank you for the response.


Sincerely

Jumia Customer Care Manager


XOXOXO

2. I received a refund of a product that I did not return. The company did not send me the product within 14 days of receipt of the product.2. As you can see from the picture in the picture, the product was not returned. It could have been refunded to the customer by the company.3. Thank you for the response.Sincerely

Jumia Customer Care Manager


XOXOXO

3. I received a refund of a product that I did not return. The company did not send me the product within 14 days of receipt of the product.3. As you can see from the picture in the picture, the product was not returned. It could