<a href="https://colab.research.google.com/github/Dennischegemwangi/code-base/blob/main/Transformers_(hugging_face).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
from transformers import pipeline

classifier = pipeline("text-classification")

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [30]:
#text classification (sentiment analysis)
import pandas as pd

output=classifier (text)
pd.DataFrame(output)

      label     score
0  NEGATIVE  0.997516

In [44]:

reader = pipeline("document-question-answering")
question = "what does the customer want?"
outputs = reader(question=question, context=text)
pd.DataFrame([outputs])

[transformers] No model was supplied, defaulted to impira/layoutlm-document-qa and revision beed3c4.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/789 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  511MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/205 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/315 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

TypeError: DocumentQuestionAnsweringPipeline.__call__() missing 1 required positional argument: 'image'

In [26]:
#named entity recognition
ner_tagger = pipeline ("ner", aggregation_strategy= "simple")
outputs = ner_tagger(text)
pd.DataFrame(outputs)

[transformers] No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  entity_group     score     word  start  end
0         MISC  0.988393  MacBook     37   44
1          ORG  0.681345    Jumia     74   79
2          LOC  0.401889     ##ja     91   93

In [39]:
text = " I was asking for a a refund for the MacBook that I returned on Friday at Jumia branch kianjai"